# Generated by Django 5.2.1 on 2025-05-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
